
Autoencoder_type:
  name: "Skip Autoencoder"
  input_shape: [128, 128, 3]
  latent_dim: 64
  optimizer: "Adam"
  loss_function: "Mean Squared Error"
  metrics: ["accuracy"]
  test_autoencoder:
    batch_size: 32
    base: 'kyoto'
    epochs: 10
    metrics_image:
      mse: 0.456
      psnr: 28.5
      ssim: 0.85
  